databases:
  - name: suber-eats
    user: suber_eats
    plan: free
    region: oregon

services:
  - type: web
    name: suber-eats
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: suber-eats
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  