export const operatingCountries = (): string[] => {
    const countries: string[] = [ 
      'Australia',
      'Belgium',
      'Bolivia',
      'Canada',
      'Chile',
      'Costa Rica',
      'Dominican Republic',
      'Ecuador',
      'El Salvador',
      'France',
      'Germany',
      'Guatemala',
      'Ireland',
      'Italy',
      'Japan',
      'Kenya',
      'Mexico',
      'Netherlands',
      'New Zealand',
      'Panama',
      'Poland',
      'Portugal',
      'South Africa',
      'Spain',
      'Sri Lanka',
      'Sweden',
      'Switzerland',
      'Taiwan (ROC)',
      'United Kingdom',
      'United States'
    ];  
    return countries;
  }